export { default as AcademicYearAverageCard } from './AcademicYearAverageCard.component';
export { default as AcademicYearModal } from './AcademicYearModal.component';
export { default as AcademicYearPartialTable } from './AcademicYearPartialTable.component';
export { default as AcademicYearTable } from './AcademicYearTable.component';
export { default as CourseScoreContent } from './CourseScoreContent.component';
export { default as GradeStudentTable } from './GradeStudentTable.component';
export { default as StudentTabs } from './StudentTabs.component';
export { default as StudentsPassedAndFailed } from './StudentsPassedAndFailedCard.component';
export { default as TopStudentsCard } from './TopStudentsCard.component';
